<?php

/*
 * Copyright (C) 2024 chris
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

/**
 * Description of config
 *
 * @author chris
 */
class configuration {

    //  getKey is a way of ensuring only authorised sites store anything via this web site.
    //  The calling site must use the same key as generated by this function for the data to be stored
    //  The domain name and ata string are passed to the function and hence you can have a static key or base it on either or these two paramaeters
    //  e.g. the $key could be something like
    //         $key = md5($domain or $data);
    //         or $key = "securitykey";
    public function getKey($domain, $json) {
        $key = md5($domain);
        return $key;
    }

    // you can provide a url that returns a list of the domains for which you expect to see web monitor data
    // this enables the software to notify you of domains that are not storing their data
    // The format of the data sent by the feed must be an object as described below
    //    {   
    //    "data": [{
    //            "domain": "hikemk.org.uk",
    //            "status": "Hosted"
    //        }, {
    //            "domain": "avon-ramblers.org.uk",
    //            "status": "Hosted"
    //        }]
    //     }
    // other properties may be present but may    be ignored
    public  $domainListUrl = "https://ramblers-webs.org.uk/index.php?option=com_rw_accounts&view=domains&format=json";
}
